module.exports =
 [
      {
        post_id: 0,
        nickname: "myomyo",
        thumbnail: "",
        title: "첫 게시글",
        content: "악 떨려욤",
        view: 22,
        like: 11,
        creatAt: "2023-03-03 16:13:22",
        commentCount: 2,
        hashTag: ["#해시태그","#해시태그2"],
        category: "recipe"
      },
      {
        post_id: 1,
        nickname: "myo",
        thumbnail: "",
        title: "글글게시글장문게시글장문게시글장문게시글장문게시글장문게시글장문게시글장문게시글장문게시글장문게시글50자까지",
        content: "장문~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
        view: 312,
        like: 111,
        creatAt: "2023-03-03 16:13:22",
        commentCount: 10,
        hashTag: [],
        category: "cocktail"
      },
      {
        post_id: 2,
        nickname: "haega",
        thumbnail: "",
        title: "테스트 게시글",
        content: "테스트 할 거니까 다 나가주세요",
        view: 0,
        like: 0,
        creatAt: "2023-03-03 16:13:22",
        commentCount: 0,
        hashTag: ["#해시태그","#해시태그2","#해시태그3"],
        category: "etc"
      },
   {
     post_id: 3,
     nickname: "haega",
     thumbnail: "",
     title: "테스트 게시글",
     content: "테스트 할 거니까 다 나가주세요",
     view: 0,
     like: 0,
     creatAt: "2023-03-03 16:13:22",
     commentCount: 0,
     hashTag: ["#해시태그","#해시태그2","#해시태그3"],
     category: "etc"
   },
   {
     post_id: 4,
     nickname: "haega",
     thumbnail: "",
     title: "테스트 게시글",
     content: "테스트 할 거니까 다 나가주세요",
     view: 0,
     like: 0,
     creatAt: "2023-03-03 16:13:22",
     commentCount: 0,
     hashTag: ["#해시태그","#해시태그2","#해시태그3"],
     category: "etc"
   },
   {
     post_id: 5,
     nickname: "haega",
     thumbnail: "",
     title: "테스트 게시글",
     content: "테스트 할 거니까 다 나가주세요",
     view: 0,
     like: 0,
     creatAt: "2023-03-03 16:13:22",
     commentCount: 0,
     hashTag: ["#해시태그","#해시태그2","#해시태그3"],
     category: "etc"
   },
   {
     post_id: 6,
     nickname: "haega",
     thumbnail: "",
     title: "테스트 게시글",
     content: "테스트 할 거니까 다 나가주세요",
     view: 0,
     like: 0,
     creatAt: "2023-03-03 16:13:22",
     commentCount: 0,
     hashTag: ["#해시태그","#해시태그2","#해시태그3"],
     category: "etc"
   },
   {
     post_id: 7,
     nickname: "haega",
     thumbnail: "",
     title: "테스트 게시글",
     content: "테스트 할 거니까 다 나가주세요",
     view: 0,
     like: 0,
     creatAt: "2023-03-03 16:13:22",
     commentCount: 0,
     hashTag: ["#해시태그","#해시태그2","#해시태그3"],
     category: "etc"
   },
   {
     post_id: 8,
     nickname: "haega",
     thumbnail: "",
     title: "테스트 게시글",
     content: "테스트 할 거니까 다 나가주세요",
     view: 0,
     like: 0,
     creatAt: "2023-03-03 16:13:22",
     commentCount: 0,
     hashTag: ["#해시태그","#해시태그2","#해시태그3"],
     category: "etc"
   },
   {
     post_id: 9,
     nickname: "haega",
     thumbnail: "",
     title: "테스트 게시글",
     content: "테스트 할 거니까 다 나가주세요",
     view: 0,
     like: 0,
     creatAt: "2023-03-03 16:13:22",
     commentCount: 0,
     hashTag: ["#해시태그","#해시태그2","#해시태그3"],
     category: "etc"
   },
   {
     post_id: 10,
     nickname: "haega",
     thumbnail: "",
     title: "테스트 게시글10",
     content: "테스트 할 거니까 다 나가주세요",
     view: 0,
     like: 0,
     creatAt: "2023-03-03 16:13:22",
     commentCount: 0,
     hashTag: ["#해시태그","#해시태그2","#해시태그3"],
     category: "etc"
   },
   {
     post_id: 11,
     nickname: "haega",
     thumbnail: "",
     title: "테스트 게시글11",
     content: "테스트 할 거니까 다 나가주세요",
     view: 0,
     like: 0,
     creatAt: "2023-02-03 16:13:22",
     commentCount: 0,
     hashTag: ["#해시태그","#해시태그2","#해시태그3"],
     category: "etc"
   },
   {
     post_id: 12,
     nickname: "haega",
     thumbnail: "",
     title: "테스트 게시글12",
     content: "테스트 할 거니까 다 나가주세요",
     view: 0,
     like: 0,
     creatAt: "2023-03-03 16:13:22",
     commentCount: 0,
     hashTag: ["#해시태그","#해시태그2","#해시태그3"],
     category: "etc"
   },
   {
     post_id: 13,
     nickname: "haega",
     thumbnail: "",
     title: "테스트 게시글13",
     content: "테스트 할 거니까 다 나가주세요",
     view: 97979,
     like: 5678,
     creatAt: "2023-01-03 16:13:22",
     commentCount: 0,
     hashTag: ["#해시태그","#해시태그2","#해시태그3"],
     category: "etc"
   },
   {
     post_id: 14,
     nickname: "haega",
     thumbnail: "",
     title: "테스트 게시글14",
     content: "테스트 할 거니까 다 나가주세요",
     view: 0,
     like: 0,
     creatAt: "2023-03-03 16:13:22",
     commentCount: 0,
     hashTag: ["#해시태그","#해시태그2","#해시태그3"],
     category: "etc"
   },
   {
     post_id: 15,
     nickname: "haega",
     thumbnail: "",
     title: "테스트 게시글15",
     content: "테스트 할 거니까 다 나가주세요",
     view: 0,
     like: 0,
     creatAt: "2023-03-03 16:13:22",
     commentCount: 0,
     hashTag: ["#해시태그","#해시태그2","#해시태그3"],
     category: "etc"
   },
   {
     post_id: 16,
     nickname: "haega",
     thumbnail: "",
     title: "테스트 게시글16",
     content: "테스트 할 거니까 다 나가주세요",
     view: 0,
     like: 0,
     creatAt: "2023-03-03 16:13:22",
     commentCount: 0,
     hashTag: ["#해시태그","#해시태그2","#해시태그3"],
     category: "etc"
   },
   {
     post_id: 17,
     nickname: "haega",
     thumbnail: "",
     title: "테스트 게시글17",
     content: "테스트 할 거니까 다 나가주세요",
     view: 0,
     like: 0,
     creatAt: "2023-03-03 16:13:22",
     commentCount: 0,
     hashTag: ["#해시태그","#해시태그2","#해시태그3"],
     category: "etc"
   },
   {
     post_id: 18,
     nickname: "haega",
     thumbnail: "",
     title: "테스트 게시글18",
     content: "테스트 할 거니까 다 나가주세요",
     view: 0,
     like: 0,
     creatAt: "2023-03-03 16:13:22",
     commentCount: 0,
     hashTag: ["#해시태그","#해시태그2","#해시태그3"],
     category: "etc"
   },
   {
     post_id: 19,
     nickname: "haega",
     thumbnail: "",
     title: "테스트 게시글19",
     content: "테스트 할 거니까 다 나가주세요",
     view: 0,
     like: 0,
     creatAt: "2023-03-03 16:13:22",
     commentCount: 0,
     hashTag: ["#해시태그","#해시태그2","#해시태그3"],
     category: "etc"
   },
    ]